//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enigma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main
    {
        public Main()
        {
            this.Plugboard = new HashSet<Plugboard>();
            this.Rotors = new HashSet<Rotors>();
        }
    
        public string Name { get; set; }
        public string Alphabet { get; set; }
        public bool Sensitivity { get; set; }
        public string Reflector { get; set; }
    
        public virtual ICollection<Plugboard> Plugboard { get; set; }
        public virtual ICollection<Rotors> Rotors { get; set; }
    }
}
